### ISSUE TITLE
How to create class without  invoking element?

### ISSUE THREAD

**Issue by sigrlami** [sebastiaanvisser/clay#11]
_How can I skip invoking elements as div, and use just "." ?_

Currently I have following code:

``` haskell
carouselS :: Css
carouselS =  ".carousel" & do
                         border    solid  (px 10)  white
                         boxShadow (em 0) (em 0.3) (em 0.8) black
                         margin    (px 0) auto auto auto
                         padding   (px 0) auto auto auto
```

Printning with:  

``` haskell
putCss $ div ? carouselS
```

Gives ouput as:

``` css
div.carousel
{
  border             : solid 10px rgb(255,255,255);
  -webkit-box-shadow : 0.0em 0.3em 0.8em rgb(0,0,0);
  -moz-box-shadow    : 0.0em 0.3em 0.8em rgb(0,0,0);
  -ms-box-shadow     : 0.0em 0.3em 0.8em rgb(0,0,0);
  -o-box-shadow      : 0.0em 0.3em 0.8em rgb(0,0,0);
  box-shadow         : 0.0em 0.3em 0.8em rgb(0,0,0);
  margin             : 0px auto auto auto;
  padding            : 0px auto auto auto;
} 
```

but I want:

``` css
.carousel
{
   ...
```
