### ISSUE TITLE
Support grouping

### ISSUE THREAD

**Issue by johannesgerer** [sebastiaanvisser/clay#128]
Support for grouping would be great (or did I miss it in the docs?):

```
h2, .thisOtherClass, .yetAnotherClass {
    color: red;
}
```

**Comment by Dridus** [comment]
`Selector` instances `Monoid` which is the abstract notion of things that can be appended to each other. In `Selector`'s case, this does what you're asking for:

```haskell
import Clay
import Data.Monoid ((<>))

main = putCss $ ("h2" <> ".thisOtherClass" <> ".yetAnotherClass") ? color red
```

yields

```css
h2,
.thisOtherClass,
.yetAnotherClass
{
  color : #ff0000;
}
```
