### ISSUE TITLE
Usage of floats causes floating errors on output

### ISSUE THREAD

**Issue by qwbarch** [sebastiaanvisser/clay#251]
When using this example css:
```haskell
"#hello-world" ?
  borderTopLeftRadius (Clay.rem 0.6) (Clay.rem 0.7)
```
This outputs the following:
```css
#hello-world
{
  border-top-left-radius : 0.59999rem 0.69999rem;
}
```

Could clay have the input switched to something like [Decimal](https://hackage.haskell.org/package/Decimal-0.5.2/docs/Data-Decimal.html) instead, so there's no floating point errors?
If a PR is welcome, I'd be happy to make the change!
