### ISSUE TITLE
How can I apply style for an elements list?

### ISSUE THREAD

**Issue by Cynede** [sebastiaanvisser/clay#4]
what am I trying to do:

``` haskell
{-# LANGUAGE OverloadedStrings #-}

import Clay

import Prelude hiding (div,span,(**))

import Data.Monoid

generalcss = foldl1 (Clay.**) [html, body, div, span, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, address, code, del, dfn, img, q, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td]

main = putCss $
  do generalcss ?
      do fontSize (em 0.6)
```

what do I get:

``` css
html body div span object iframe h1 h2 h3 h4 h5 h6 p blockquote pre a abbr address code del dfn img q dl dt dd ol ul li fieldset form label legend table caption tbody tfoot thead tr th td
{
  font-size : 0.6em;
}
```

How to make it proper? Though there should be comas...
